spring:
  application:
    name: api-gateway
  cloud:
    consul:
      enabled: false
      host: localhost
      port: 8500
      discovery:
        ip-address: true
        health-check-interval: 10s
        health-check-path: /actuator/health
    discovery:
      enabled: false
    gateway:
      mvc:
        routes:
          - id: ecommerce
            uri: http://localhost:8080
            predicates:
              - Path=/direct/**
            filters:
              - StripPrefix=1
          - id: service2
            uri: http://localhost:8081
            predicates:
              - Path=/redirect/**
            filters:
              - StripPrefix=1
server:
  port: 8000
